[package]
name = "rysto"
version = "0.1.0"
authors = ["Luis de Bethencourt <luisbg@amazon.com>"]
edition = "2018"

[dependencies]
hex = "~0.3.2"
base64 = "~0.6.0"
ascii = "0.9.0"
rust-crypto = "0.2.36"
rand = "0.5.4"
